name: "Get The Default Branch"
decription: "Get the default branch for this repository"
branding:
  icon: 'git-branch'
  color: 'green'
outputs:
  default_branch:
    description: "The default branch name"
    value: ${{ steps.default-branch-name.outputs.default-branch }}
runs:
  using: 'composite'
  steps:
    - id: default-branch-name
      shell: bash
      run: |
        echo ::set-output name=default-branch::$(curl -s https://api.github.com/repos/${{ github.repository }} -H "Authorization: bearer ${{ github.token }}" | jq -r .default_branch)